name: Nexjs Docker Image

on:
  push:
    branches: ['develop']
jobs:
  buildservice:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: generate buildnumber
        id: buildnumber
        uses: einaregilsson/build-number@v3
        with:
          token: ${{secrets.github_token}}

      - name: checkout service
        uses: actions/checkout@v2
        with:
          path: service

      - name: read docker properties
        uses: madhead/read-java-properties@latest
        id: docker
        with:
          file: service/docker.properties
          all: true

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: yarn install --frozen-lockfile
        working-directory: ./service

      - name: Build app
        run: yarn build
        working-directory: ./service

      - name: dockerhub login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: push docker image
        uses: docker/build-push-action@v2
        with:
          context: ./service
          push: true
          tags: |
            jfcbxp/${{ steps.docker.outputs.IMAGE_NAME }}:${{ steps.docker.outputs.MAJOR_VERSION }}.${{ steps.docker.outputs.MINOR_VERSION }}.${{ steps.buildnumber.outputs.build_number }}
            jfcbxp/${{ steps.docker.outputs.IMAGE_NAME }}:latest
          build-args: |
            ARTIFACT_NAME=${{ steps.docker.outputs.ARTIFACT_NAME }}
            IMAGE_VERSION=${{ steps.docker.outputs.IMAGE_NAME }}:${{ steps.docker.outputs.MAJOR_VERSION }}.${{ steps.docker.outputs.MINOR_VERSION }}.${{ steps.buildnumber.outputs.build_number }}
