name: Nextjs Docker Image

on:
  push:
    branches: ['develop', 'main', 'test']
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate build number
        id: buildnumber
        uses: einaregilsson/build-number@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Read Docker properties
        uses: madhead/read-java-properties@latest
        id: docker
        with:
          file: docker.properties
          all: true

      - name: Define ENV vars based on branch
        run: |
          if [[ "${GITHUB_REF##*/}" == "develop" ]]; then
            echo "ENVIRONMENT=dev" >> $GITHUB_ENV
            echo "IMAGE_SUFFIX=dev" >> $GITHUB_ENV
          elif [[ "${GITHUB_REF##*/}" == "main" ]]; then
            echo "ENVIRONMENT=prd" >> $GITHUB_ENV
            echo "IMAGE_SUFFIX=prd" >> $GITHUB_ENV
          else
            echo "ENVIRONMENT=tst" >> $GITHUB_ENV
            echo "IMAGE_SUFFIX=tst" >> $GITHUB_ENV
          fi

      - name: Compose full image name
        run: |
          echo "FULL_IMAGE_NAME=${{ steps.docker.outputs.IMAGE_NAME }}-${IMAGE_SUFFIX}" >> $GITHUB_ENV

      - name: DockerHub login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            jfcbxp/${{ env.FULL_IMAGE_NAME }}:${{ steps.docker.outputs.MAJOR_VERSION }}.${{ steps.docker.outputs.MINOR_VERSION }}.${{ steps.buildnumber.outputs.build_number }}
            jfcbxp/${{ env.FULL_IMAGE_NAME }}:latest
          build-args: |
            ENVIRONMENT=${{ env.ENVIRONMENT }}
